---

- name: Update domain_name in dmapi.conf
  shell: |
    sed -i '/project_domain_name = /c project_domain_name = Default' dmapi.conf
    sed -i '/user_domain_name = /c user_domain_name = Default' dmapi.conf
  args:
    chdir: /etc/dmapi


