---
- name: ensure tvault-object-store service is stopped
  service: name=tvault-object-store  state=stopped enabled=no
  ignore_errors: yes

- name: stop datamover extension service
  service: name=tvault-contego state=stopped enabled=no
  ignore_errors: yes

- name: Remove trilio yum repo
  file: path="{{trilio_yum_repo_file_path}}" state=absent

- name: uninstall tvault contego extension packages when using python2
  yum:
     name:
        - python-s3fuse-plugin-cent7
        - tvault-contego
        - puppet-triliovault
     state: absent
  when: PYTHON_VERSION=="python2"

- name: uninstall tvault contego extension | python3-s3fuse-plugin | centos-release-openstack-{{OPENSTACK_DIST}} packages when using python3
  yum:
     name:
        - "centos-release-openstack-{{OPENSTACK_DIST | lower}}"
        - python3-s3fuse-plugin
        - python3-tvault-contego
        - puppet-triliovault
     state: absent
  when: PYTHON_VERSION=="python3"

