---
- block:
  - name: Find horizon container name
    find:
      patterns: '*_horizon_*'
      paths:
        - /var/lib/lxc
      file_type: directory
    register: file_found

  - set_fact:
      horizon_containers_names: "{{ horizon_containers_names|default([]) + [ item.path.split('/')[4] ]}}"
    loop: "{{file_found.files}}"

  - debug:
      msg: "{{horizon_containers_names}}"
      verbosity: "{{verbosity_level}}"

  - name: Get containers info
    lxc_container:
      name: "{{item}}"
    register: horizon_containers_info
    with_items: "{{ horizon_containers_names }}"

  - set_fact:
      horizon_container_ips: "{{ horizon_container_ips|default([]) + [ item.lxc_container.ips.1 ]}}"
    loop: "{{horizon_containers_info.results}}"

  - name: Horizon container Ip-address
    debug:
      msg: "{{horizon_container_ips}}"
      verbosity: "{{verbosity_level}}"

  - name: Find python version of horizon service
    shell: lxc-attach -n {{ horizon_containers_names[0] }} -- bash -c "cd /openstack/venvs/horizon*/lib/ &&  ls -l | grep python3 | grep -v grep > /dev/null && echo 'python3' || echo 'python2'"
    register: python_result

  - set_fact: PYTHON_VERSION={{ python_result.stdout }}
  - debug:
      msg: "PYTHON_VERSION: {{PYTHON_VERSION}}"
      verbosity: "{{ verbosity_level }}"

  - name: install packages on horizon container | curl
    shell: lxc-attach -n {{ item }} -- bash -c "apt-get install curl -y"
    when: ansible_distribution=="Ubuntu"
    retries: 3
    delay: 3
    register: result
    until: result.rc == 0
    with_items: "{{horizon_containers_names}}"

  - name: Find openstack-dashboard path in horizon container
    find:
      patterns: 'site-packages'
      paths:
        - /var/lib/lxc/{{ horizon_containers_names[0] }}/rootfs/openstack/
      file_type: directory
      recurse: yes
    register: file_found

  - set_fact: HORIZON_PATH="{{ (file_found.files[0]['path']).split('rootfs')[1] }}"

  - debug:
      msg: "{{HORIZON_PATH}}"
      verbosity: "{{verbosity_level}}"

  - name: Register the hosts and Variable in the inventory
    add_host:
      name: "{{item}}"
      group: "tvault_horizon_container_hosts"
      HORIZON_PATH: "{{ HORIZON_PATH }}"
      PYTHON_VERSION: "{{ PYTHON_VERSION }}"
    with_items: "{{ horizon_container_ips }}"
  tags:
    - tvault-horizon
    - tvault-all-install
    - tvault-horizon-uninstall
    - tvault-all-uninstall



