---

- hosts: "{{tvault_horizon_hosts}}"
  tasks:
  - include : ansible-horizon-plugin-helper.yml

- hosts: tvault_horizon_container_hosts
  roles:
    - role: ansible-horizon-plugin

- hosts: controller
  roles:
    - role: ansible-datamover-api

- hosts: compute
  roles:
    - role: ansible-tvault-contego-extension